### ISSUE TITLE
Events Epic

### ISSUE THREAD

**Issue by manuelportela** [mint-vernetzt/mint-vernetzt#150]
# Detail

- [x] #241
- [x] #194

# Model Events
- [x] #151
- [x] #152

# Contact component
- [x] #155

# On Event List
- [x] #163
- [x] #153
- [ ] #154
- [x] #158

# Event Detail Utility
- [x] #159
- [x] If Parent with children: show child navigation
- [x] If Child with siblings: show child navigation
- [x] If Child with siblings: back button to parent
- [x] if parent has contact display contact component

# Event Detail Content
- [x] If Parent: show child overview in content after own body (link items to detail page of children)
- [x] If Child: show feature image + headline + tags of parent if applicable
- [x] #157
Headline/TimeFrom/TimeTo/Body (innerBlock)
